let tasks=JSON.parse(localStorage.getItem('tasks')||'[]');
let market=JSON.parse(localStorage.getItem('market')||'[]');
let categories=JSON.parse(localStorage.getItem('categories')||'["Lavagem","Limpeza","Organização"]');
function saveAll(){localStorage.setItem('tasks',JSON.stringify(tasks));localStorage.setItem('market',JSON.stringify(market));localStorage.setItem('categories',JSON.stringify(categories));}
function byId(id){return document.getElementById(id)}
function escapeHtml(text){return String(text).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function formatDate(date){if(!date)return'';const[y,m,d]=date.split('-');return `${d}/${m}/${y}`}
function renderStats(){byId('totalTasks').innerText=tasks.length;byId('totalCats').innerText=categories.length;byId('totalItems').innerText=market.length;byId('totalChecked').innerText=market.filter(item=>item.checked).length}
function renderCategories(){const taskCategory=byId('taskCategory');const filterCategory=byId('filterCategory');const categoryList=byId('categoryList');const selectedTaskCategory=taskCategory.value;const selectedFilterCategory=filterCategory.value;taskCategory.innerHTML='<option value="">Selecione...</option>';filterCategory.innerHTML='<option value="">Todas as categorias</option>';categoryList.innerHTML='';categories.forEach((category,index)=>{const safeCategory=escapeHtml(category);taskCategory.innerHTML+=`<option value="${safeCategory}">${safeCategory}</option>`;filterCategory.innerHTML+=`<option value="${safeCategory}">${safeCategory}</option>`;categoryList.innerHTML+=`<div class="d-flex justify-content-between align-items-center border rounded p-2 mb-2 bg-white"><span><i class="bi bi-tag"></i> ${safeCategory}</span><button class="btn btn-sm btn-outline-danger" onclick="deleteCategory(${index})"><i class="bi bi-trash"></i></button></div>`});taskCategory.value=selectedTaskCategory;filterCategory.value=selectedFilterCategory;renderStats()}
function addCategory(){const input=byId('newCategory');const name=input.value.trim();if(!name)return;const exists=categories.some(c=>c.toLowerCase()===name.toLowerCase());if(exists){alert('Essa categoria já existe.');return}categories.push(name);categories.sort((a,b)=>a.localeCompare(b));input.value='';saveAll();renderCategories()}
function deleteCategory(index){const category=categories[index];const inUse=tasks.some(task=>task.category===category);if(inUse){alert('Não é possível excluir uma categoria que já está sendo usada em tarefas.');return}if(!confirm('Excluir esta categoria?'))return;categories.splice(index,1);saveAll();renderCategories()}
byId('taskForm').addEventListener('submit',function(event){event.preventDefault();const id=byId('taskId').value;const task={id:id||Date.now(),date:byId('taskDate').value,category:byId('taskCategory').value,description:byId('taskDescription').value.trim()};if(!task.category){alert('Selecione uma categoria.');return}if(id){const index=tasks.findIndex(item=>item.id==id);tasks[index]=task}else{tasks.push(task)}saveAll();clearTaskForm();renderTasks()});
function clearTaskForm(){byId('taskForm').reset();byId('taskId').value=''}
function renderTasks(){const filter=byId('filterCategory').value;const search=byId('searchTask').value.trim().toLowerCase();const list=byId('tasksList');let data=[...tasks];if(filter){data=data.filter(task=>task.category===filter)}if(search){data=data.filter(task=>task.description.toLowerCase().includes(search)||task.category.toLowerCase().includes(search))}data.sort((a,b)=>String(b.date).localeCompare(String(a.date)));if(!data.length){list.innerHTML='<div class="empty-state">Nenhuma tarefa encontrada.</div>'}else{list.innerHTML=data.map(task=>`<div class="card card-body shadow-sm mb-2 task-card"><div class="d-flex justify-content-between flex-wrap gap-2"><div><span class="category-pill">${escapeHtml(task.category)}</span><div class="mt-2"><strong>${formatDate(task.date)}</strong></div><div>${escapeHtml(task.description)}</div></div><div class="actions"><button class="btn btn-sm btn-warning" onclick="editTask(${task.id})"><i class="bi bi-pencil"></i> Editar</button><button class="btn btn-sm btn-danger" onclick="deleteTask(${task.id})"><i class="bi bi-trash"></i> Excluir</button></div></div></div>`).join('')}renderStats();renderCategories()}
function editTask(id){const task=tasks.find(item=>item.id==id);if(!task)return;byId('taskId').value=task.id;byId('taskDate').value=task.date;byId('taskCategory').value=task.category;byId('taskDescription').value=task.description;window.scrollTo({top:0,behavior:'smooth'})}
function deleteTask(id){if(!confirm('Excluir esta tarefa?'))return;tasks=tasks.filter(item=>item.id!=id);saveAll();renderTasks()}
byId('filterCategory').addEventListener('change',renderTasks);byId('searchTask').addEventListener('input',renderTasks);
byId('marketForm').addEventListener('submit',function(event){event.preventDefault();const id=byId('marketId').value;const item={id:id||Date.now(),text:byId('marketItem').value.trim(),checked:false};if(!item.text)return;if(id){const index=market.findIndex(marketItem=>marketItem.id==id);item.checked=market[index].checked;market[index]=item}else{market.push(item)}saveAll();byId('marketForm').reset();byId('marketId').value='';renderMarket()});
function renderMarket(){const list=byId('marketList');if(!market.length){list.innerHTML='<div class="empty-state">Nenhum item na lista de compras.</div>'}else{list.innerHTML=market.map(item=>`<div class="card card-body shadow-sm mb-2 market-card ${item.checked?'checked':''}"><div class="d-flex justify-content-between align-items-center flex-wrap gap-2"><label class="d-flex align-items-center gap-2"><input type="checkbox" class="form-check-input" ${item.checked?'checked':''} onchange="toggleItem(${item.id})"><span class="${item.checked?'item-checked':''}">${escapeHtml(item.text)}</span></label><div class="actions"><button class="btn btn-sm btn-warning" onclick="editItem(${item.id})"><i class="bi bi-pencil"></i> Editar</button><button class="btn btn-sm btn-danger" onclick="deleteItem(${item.id})"><i class="bi bi-trash"></i> Excluir</button></div></div></div>`).join('')}renderStats()}
function toggleItem(id){const item=market.find(item=>item.id==id);if(!item)return;item.checked=!item.checked;saveAll();renderMarket()}
function editItem(id){const item=market.find(item=>item.id==id);if(!item)return;byId('marketId').value=item.id;byId('marketItem').value=item.text;byId('marketItem').focus()}
function deleteItem(id){if(!confirm('Excluir este item?'))return;market=market.filter(item=>item.id!=id);saveAll();renderMarket()}
function exportBackup(){const data={tasks,market,categories,exportedAt:new Date().toISOString()};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='backup-organizador-pro-v2.json';link.click()}
byId('importBackupInput').addEventListener('change',function(event){const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=function(){try{const data=JSON.parse(reader.result);tasks=Array.isArray(data.tasks)?data.tasks:[];market=Array.isArray(data.market)?data.market:[];categories=Array.isArray(data.categories)?data.categories:categories;saveAll();renderCategories();renderTasks();renderMarket();alert('Backup importado com sucesso.')}catch{alert('Arquivo de backup inválido.')}};reader.readAsText(file)});
renderCategories();renderTasks();renderMarket();if('serviceWorker'in navigator){navigator.serviceWorker.register('sw.js')}
